"""Add_user_admin

Revision ID: d29bc87a4d48
Revises: 6b91c86fb112
Create Date: 2026-02-22 17:25:21.629273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd29bc87a4d48'
down_revision: Union[str, Sequence[str], None] = '6b91c86fb112'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Очистка таблицы products перед добавлением нового столбца
    op.execute("DELETE FROM products")
    
    # Очистка таблицы categories перед добавлением нового столбца 
    op.execute("DELETE FROM categories")

    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('admin_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'categories', 'users', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'admin_id')
    # ### end Alembic commands ###
